title: Jason Taekyun Kim
name: Taekyun Kim
email: saurus234@gmail.com
description: >-
  Node.js Server Developer

baseurl: ""
url: "https://jasonTaekyun.github.io"

# profile 이미지
profile_image: images/me.jpg

# SNS 아이디
# facebook_id: babycheetah
# instagram_id: babycheetah

# Youtube vid
youtube_vid: #

# Custom Color
primary: 2c98f0 #b72cf0
primary_hover: 44A4F2 #9a2dc7
color_1: 2c98f0 #b72cf0
color_2: ec5453
color_3: f9bf3f
color_4: a84cb8
color_5: 2fa499
color_6: 4054b2

# slider type 0  (텍스트가 우측 정렬된 슬라이더)
slider_0: # 형식에 맞추어 항목 추가
  - background_url: images/img_bg_6.jpeg
    title: 안녕하세요. <br>반갑습니다!</br>
    transform: translate( -50%, -50%)
    left: -180px
    bottom: -50px

# slider type 1  (텍스트가 좌측 정렬된 슬라이더)
slider_1: # 형식에 맞추어 항목 추가
  - background_url: images/img_bg_5.jpg
    title: I am<br>SERVER Developer
    subtitle: >-
      모르는 것은 찾아보고<br>
      팀원들과 소통하며<br>
      최선의 결과를 이끌어가는<br>
      신입 서버 개발자 김태균입니다.

# About
about_meta: About Me
about_header: >-
  "걸어다니는 위키피디아"
about_introduce: >-
  "안녕하세요. 새로운 개념을 바로 찾아보고 팀원들과 공유하면서 생산성을 높이는 개발자 김태균입니다."
about_content: >-
  프로젝트 진행시 문제에 직면하면 먼저 <strong>해결법을 찾아보고, 적용</strong>합니다.<br>
  적용한 내용을 팀원들과 공유하고 새로 얻은 지식을 <strong>전달해주는 것</strong>을 좋아합니다.<br>
  버거워하는 팀원이 있으면 이끌어주고 <strong>팀으로서</strong> 프로젝트를 완성하는 것에 초점을 맞춥니다.<br>
  무엇보다도, 프로젝트의 방향에 맞게 결과물을 도출해내기 위해 <strong>고민하고 끊임없이 소통</strong>합니다.<br><br>
  개발자라면 누구든지 처음 시작하게 되면 문제에 직면하게 됩니다.<br>
  에러에 부딫히고 문제를 만나며 성장하게 되는 과정 속에서 저는 해결책을 찾기 위해 부단히 노력하였습니다.<br>
  팀원들 사이에서 저는 "걸어다니는 위키피디아”로 불렸을 정도로 모르는 정보는 찾아보고, 적용하여 끝내 해결책을 찾아 공유했습니다.<br>
  <strong>주당 100시간의 몰입을 통해 얻은 성취감을 사랑합니다!</strong>

about_services: # 형식에 맞추어 항목 추가
  - icon: icon-data
    name: Server
  - icon: icon-monitor
    name: Web
  - icon: icon-lightbulb
    name: AWS
  - icon: icon-code
    name: JavaScript

    # 나의 좌우명이나 각오를 적는 칸
about_box_content: <strong>커밋이 미래다!</strong> <br> <strong>1일 1커밋</strong>을 통해 매일 꾸준하게 성장하려고 노력중입니다.<br>
about_box_button:
  link: https://github.com/taekyunJason
  name: 실력있는, 함께 일하고 싶은 서버 개발자가 되겠습니다!

# Tech  skill
tech_meta: TECH SKILLS
tech_header: 저는 지금 이것을 할 수 있습니다.
tech_content: #
tech_list: # 형식에 맞추어 항목 추가
  - name: JavaScript
    color: color-1
    animation: fadeInLeft
    percent: 50
    mark: 50
    content: JavaScript의 기본 문법을 익히고, Jquery를 통해 직접 웹 프론트에서 동작하도록 구현하고, Ajax를 통해 서버와 통신하며 게시글 기능 등을 직접 구현하였습니다.
  - name: 크롤링 Crawling
    color: color-2
    animation: fadeInRight
    percent: 50
    mark: 50
    content: 프로젝트에서 필요한 데이터를 고민하고, Puppeteer를 사용하여 웹 브라우저에서 데이터를 직접 크롤링하였습니다. 해당 데이터를 원하는 형태로 가공하여 표현했습니다.
  - name: AWS
    color: color-3
    animation: fadeInLeft
    percent: 30
    mark: 30
    content: AWS EC2와 RDS로 프로젝트 진행을 했습니다. 또한 S3와 multer를 사용하여 이미지를 업로드하는 예제를 구현했습니다. 현재 ELB와 Auto Scaling에 대해 학습중입니다.
  - name: Github
    color: color-4
    animation: fadeInRight
    percent: 40
    mark: 40
    content: 대부분의 프로젝트를 github를 통해 소스 코드를 관리하였으며, 협업 역시 github을 통해 진행하였습니다. 또한 github서버를 활용하여 포트폴리오 사이트를 관리합니다.
  - name: SQL
    color: color-5
    animation: fadeInRight
    percent: 30
    mark: 30
    content: 마지막 프로젝트를 MySQL의 시퀄라이즈를 적용하여 진행했습니다. 또한 기본적인 DB와 Table을 다루고, 데이터의 CRUD를 쿼리문으로 사용가능합니다.
  - name: NodeJs
    color: color-6
    animation: fadeInRight
    percent: 50
    mark: 50
    content: 프로젝트를 진행하면서 NodeJs의 사용법과 기능을 익혔습니다. 또한 RESTful하게 API를 작성했습니다.

tech_desc: 앞으로도 보안상 이슈가 없고, 더 나은 서비스를 제공하기 위해서 <strong>ELB, Auto Scaling, Docker, CI/CD, TypeScript</strong>등을 꾸준히 공부할 생각입니다.

# Project
project_meta: My Work
project_header: PROJECT
project_introduce: 저의 <strong>Project</strong>를 소개합니다.
project_load_more: 앞으로 더 많은 프로젝트가 추가될 예정입니다:) # 더보기 내용
project_load_more_url: https://github.com/taekyunJason

project_my_name: 개인프로젝트

project_my: # 형식에 맞추어 항목 추가
  - background_url: images/personal_project1.PNG
    animation: fadeInLeft
    name: 영양소 [영양사들의 식단 저장소](2022.06)
    description: 그동안 배웠던 기능들에 대해서 프론트(HTML)와 백엔드를 처음부터 끝까지 제작해보았습니다. MVP 구현을 위해서 기본적인 CRUD 기능에 집중하여 메뉴를 등록하고, 해당 메뉴에 대한 식재료와 1인량을 등록하고 공유할 수 있는 사이트를 만들어 보았습니다.
    detail_url: https://youtu.be/xBmb64PJZ68
    readmore_url: images/myProj01.pdf

project_team_name: 팀프로젝트
project_team: # 형식에 맞추어 항목 추가
  - background_url: images/team_project0.PNG
    animation: fadeInRight
    name: 날씨야 뭐볼래? (2022.03)
    description: 사용자의 위치를 실시간으로 불러오고, 날씨에 따라 어울리는 영화장르를 필터링해서 보여주고 예매사이트로 이동가능한 사이트를 만들었습니다
    detail_url: https://www.youtube.com/watch?v=lmdDV4PuJJQ&list=PLsIuQ8zpbUGThrDegnbOykv6emSydoasl&index=6
    readmore_url: images/proj01.pdf

  - background_url: images/team_project.PNG
    animation: fadeInRight
    name: 개발자를 위한 꿀템 추천샵 [개 꿀 샵] (2022.04)
    description: 사용자가 사용하면서 좋았던 제품들을 카테고리 별로 등록해서 다른 유저들과 공유하고 좋아요를 많이 받은 순으로 랭킹을 매겨 메인화면에 노출시키고 댓글로 소통이 가능한 사이트를 만들었습니다
    detail_url: https://www.youtube.com/watch?v=hOhe9zBMHho&list=PLsIuQ8zpbUGThrDegnbOykv6emSydoasl&index=44
    readmore_url: images/proj02.pdf

  - background_url: images/team_project1.PNG
    animation: fadeInRight
    name: 마켓컬리 클론코딩 (2020.05)
    description: 마켓컬리의 주요 기능들을 만들고 구현해본 사이트를 만들었습니다
    detail_url: https://www.youtube.com/watch?v=Y2HT10AfHao
    readmore_url: images/proj03.pdf

  - background_url: images/team_project5.PNG
    animation: fadeInRight
    name: Soldier Challengers [솔져 챌린저스] (2020.05)
    description: 현재 군대에서 복무중이지만 사회로의 복귀가 막연하고 두려운 군인들에게 취업으로 시작해서 그들의 인생 전반에 걸쳐 도전하고자 하는 것들을 스스로 설정해서 성취하는 챌린지 사이트를 만들었습니다
    detail_url: https://youtu.be/MD96bE9T1EI
    readmore_url: images/proj04.pdf

  - background_url: images/team_project2.PNG
    animation: fadeInRight
    name: Peer Review (2020.03 - 06)
    description: 웹개발을 하면서 진행했던 팀프로젝트를 함께 했던 팀원들에게 동료평가를 받았습니다.
    detail_url: https://dev-coderkim.tistory.com/108
    readmore_url: https://dev-coderkim.tistory.com/108

# Experience
exp_meta: What have I achieved?
exp_header: 저는 이런 "경험"들을 해봤습니다.
exp_content: 저는 영업직 종사, 온라인 스토어 운영 등의 경험을 통해 고객의 니즈를 파악하고 노출시키는 마케팅 능력을 갖추게 되었습니다.
exp_services: # 형식에 맞추어 항목 추가
  - name: 300명 이상 영업
    color: color-1
    icon: icon-refresh
    content: 영업 직무를 통해 300명 이상의 고객들과 고객사와 직접 만나 이야기하며 영업했습니다. 이를통해 소통의 중요성을 깨달았습니다.
  - name: 해외 트렌드 분석
    color: color-2
    icon: icon-chart-area
    content: 포장재(캔) 영업을 하면서 해외의 트렌드를 조사하고 분석하여 발표했습니다. 회사의 신사업을 추진함에 있어 도움이 될 수 있습니다. <br>
  - name: 회사 운영
    color: color-3
    icon: icon-home
    content: 웹사이트 "정성식탁"을 운영하며 비즈니스의 흐름과 본질에 대해 이해하고 6개월만에 매출 600만원을 달성할 수 있었습니다.<br>
  - name: 기술
    color: color-4
    icon: icon-bulb
    content: 폴리텍 대학교에서 개발을 시작하면서 C언어와 C#으로 유니티  엔진을 공부했고, 서버 프로그래머가 되고 싶어서 다시 한번 항해99에 참여하여 웹개발을 시작했습니다.
  - name: 헬스케어
    color: color-1
    icon: icon-starburst
    content: 트레이너를 하면서 회원님들의 체력을 관리하면서 건강과 꾸준함의 중요성에 대해 느끼고, 매일 체력관리를 하고 있습니다.<br><br>
  - name: 1일 1커밋
    color: color-6
    icon: icon-upload
    content: 웹 개발을 시작하고나서 매일 1일 1커밋을 목표로 개발을 하고 있습니다. 이를통해 매일 나아지는 발전하는 삶을 지향합니다.<br><br>

exp_counters:
  - name: Sales
    count: 300
    speed: 10000
  - name: Web Project
    count: 6
    speed: 5000
  - name: Web Project
    count: 6
    speed: 5000
  - name: Management
    count: 1
    speed: 5000

# Career
carerr_meta: career
career_header: Work Career
career_list:
  - name: 정성식탁 운영 및 관리
    date: 2019.11~2021.11
    content: 네이버 스마트 스토어 [정성식탁]을 2년간 운영했습니다. 사용자들에게 정성스런 음식을 대접하는 식탁에서의 시간처럼 합리적인 제품을 합리적인 가격에 제공한다는 비전을 가지고 운영했습니다. 온라인 사업을 운영하면서 고객의 니즈를 파악하고 상품을 마케팅하는 능력을 갖추게 되었습니다. 고객의 입장에서 생각하여 상세 페이지를 제작하고 소비자들이 느낄수 있는 불편한 점을 해소해주기 위해 노력했습니다. <br>그 결과, 시작한지 6개월만에 매출 700만원을 달성했고, 7개월만에 "파워"등급의 스토어를 달성했습니다. 이 과정을 통해 다양한 사람들과 소통하는 방법과 온라인 마케팅 능력을 갖추게 되었습니다.
    color: color-1
    icon: icon-pen2
    animation: fadeInLeft
  - name: 동원 테크팩솔루션 포장재 영업 및 거래처 관리
    date: 2018.12~2019.11
    content: 동원 [테크팩 솔루션]에서 포장재 영업 및 거래처 관리를 했습니다. 약 40개의 수제맥주 거래처, 300명 이상의 담당자들과 거래를 하였습니다. 연간 1000만관의 CAN 생산 일정을 조율하고, 거래처와 본사 생산 공장의 중간다리가 되어 CAN의 시작부터 끝까지 담당하였습니다. <br>이 과정을 통해 B2B 영업 프로세스를 알 수 있었고, 거래처 사람들과 조율하며 설득하는 방법을 알 수 있었습니다. <br>또한 해외 동향을 조사하여 회사의 신사업 추진에 있어, 아이디어를 제시하였습니다. <br>이처럼 근무하는 회사에서도 새로운 방향성을 제시하면서 회사와 함께 발전하는 사람입니다.
    color: color-2
    icon: icon-pen2
    animation: fadeInRight
  - name: 스포애니 트레이너
    date: 2017.06~2018.05
    content: 스포애니에서 트레이너로 근무하면서, 회원들의 체력증진과 삶의 질 개선에 도움을 주었습니다. 그리고 몸이 불편한 회원님을 위해 필요한 마사지와 생리학을 공부하여 서비스의 질을 높여, 입소문이 나면서 매출이 15% 증가했습니다. <br>이 과정을 통해 주인의식을 갖고 업무를 하는 것이 중요하다는 것을 배웠고, 개인적으로도 건강한 신체 단련을 통하여 스트레스를 관리하는 방법을 배웠습니다. <br>현재까지도 운동이 취미이고, 어려운 일이 있더라도 포기하지 않고 끈기있게 실행하는 힘을 길렀습니다.
    color: color-3
    icon: icon-pen2
    animation: fadeInRight

# Education
edu_meta: Education
edu_header: Education
edu_list:
  - title: Hanghae 99
    subtitle: 스파르타 코딩클럽 [항해99] 수강
    date: 2022.03 - 현재
    content: 스파르타 코딩클럽 [항해99] 과정을 수강하며, 컴퓨터 사이언스와 JavaScript 및 Node.js 프레임워크에 대해 배우며 웹 서버 개발자로 성장하기 위한 교육을 받고 팀원들과 프로젝트를 수행중입니다. 추가적으로 AWS를 활용한 배포, Git을 통한 소스코드 관리등을 진행하고 있습니다. 그리고 문제가 발생했을때 필요한 내용을 구글링하는 능력을 기를수 있었습니다.
  - title: Korea Polytechnics
    subtitle: 한국 폴리텍 대학 증강현실시스템과 수료
    date: 2021.03 - 2021.09
    content: 한국 폴리텍 대학 증강현실시스템과를 수강했습니다. 수강을 하며 C와 C#을 배우며 프로그래밍에 대한 기본적인 지식과 유니티 엔진에 대해 공부했습니다. 또한 여러 게임 프로그래밍을 하면서 에러를 만나면 찾아보고 해결하는 능력을 기를 수 있었습니다.
  - title: Incheon National University
    subtitle: 인천대학교 법학과 졸업
    date: 2011.03 - 2019.08
    content: 인천대학교 법학과에 입학하여 법에 대한 전반적인 법학을 공부하고 지식을 습득했습니다. 학과의 특성상 발표와 토론 수업이 많았는데, 이 과정을 통해서 제 의견을 논리적으로 전달하고, 상대방과 효과적으로 의사소통하는 방법을 습득할 수 있었습니다. 실제로 이후에 제가 배우고 습득했던 내용들이 고객들과 동료들과 협업하는데 큰 도움이 되었습니다.

# Blog
blog_meta: self-improvement
blog_header: BLOG and YOUTUBE
blog_load_more: 더 발전하기 위해 항상 노력합니다! :) # 더보기 내용
blog_load_more_url: #
blog_list:
  - title: 배워서 남주는 개발자 블로그
    subtitle: 개발 블로그 운영
    date: 2022.03
    content: 2월 13일부터 시작해서 현재까지 모르거나 찾아본 <strong>96개</strong>의 주제애 대해서 공부하고 포스팅 했습니다. 어제보다 더 나아지자는 생각으로 제가 새로 알게된 내용이나 평소에 궁금했던 내용들로 구성하여 꾸준히 개발 블로그를 운영해오고 있습니다.
    thumbnail_url: images/blog-1.PNG
    link: https://dev-coderkim.tistory.com
  - title: Youtube 채널 운영
    subtitle: 개발관련 및 일상 관련 유튜브 채널 운영
    date: 2022.01
    content: 웹개발을 시작하고 현재까지 <strong>95개</strong>의 영상을 업로드 했습니다. 매일 매일 TIL을 노션에 정리해서 해당 노션을 바탕으로 그날 진행했던 내용과 느낀점들을 정리하고 있습니다. 유튜브 채널을 운영하며 하루를 정리하며 배운 것들을 정리해서 영상을 촬영하고 있습니다.
    thumbnail_url: images/blog-2.PNG
    link: https://www.youtube.com/channel/UCrBDm1wjqWfGbNfn-g18fxw
  - title: 1일 1커밋 잔디심기
    subtitle: Github 잔디심기
    date: 2022.03
    content: 웹 개발을 시작하고, 1일 1커밋을 목표로 개발을 진행하고 있습니다. 꾸준하게 개발에 대한 감을 놓치지 않으려고 노력중입니다.
    thumbnail_url: images/blog-3.PNG
    link: https://github.com/taekyunJason

# Contact
contact_meta: Get in Touch
contact_header: Contact
contact_list:
  - title: saurus234@gmail.com
    icon: icon-globe-outline
  - title: 경기도 광명시 오리로
    icon: icon-map
  - title: +82 10 3359 9726
    icon: icon-phone
  - title: https://github.com/taekyunJason
    icon: icon-layers2
    url: https://github.com/taekyunJason
contact_message: <em>연락해주셔서 감사합니다.</em> 24시간이내에 회신드리도록 하겠습니다.

optional_front_matter:
  remove_originals: true
